[package]
name = "firewall-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
dialoguer = "0.11"
pnet = "0.34"
firewall-common = { path = "../firewall-common" }
ctrlc = "3.4"
